version: '3'
services:
  db:
    image: 'mysql:5.7'
    container_name: 'mysqldb'
    volumes:
      - '${MYSQL_LOCAL_PATH}:/var/lib/mysql'
    restart: 'on-failure'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
  api:
    container_name: 'microcontainers-api'
    image: 'microcontainers:latest'
    ports:
      - 4000:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?autoReconnect=true&useSSL=false&maxReconnects=30
      SPRING_DATASOURCE_USER: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
