version: '3'
services:
  api:
    image: ewertonvd/api-java-mysql:1.0
    ports:
      - "4000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fiapdb?autoReconnect=true&useSSL=false&maxReconnects=30
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: senhaFiap
    depends_on:
      - mysql
    deploy:
      replicas: 3
      #update_config:
      #  parallelism: 1
      #  delay: 10is
      mode: replicated
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: fiapdb
      MYSQL_ROOT_PASSWORD: senhaFiap
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure

volumes:
  db-data: